apiVersion: apps/v1
kind: Deployment
metadata:
  name: letscode-backend
spec:
  selector:
    matchLabels:
      app: letscode-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: letscode-backend
    spec:
      containers:
      - name: letscode-backend
        image: dig0w/letscode_be
        env:
        - name: MYSQL_DB_HOST
          value: MY_DB_URL #change it
        - name: MYSQL_DB_USER
          value: MYUSER #change it
        - name: MYSQL_DB_PASSWORD
          value: MYPASS #change it
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: letscode-backend-svc
spec:
  selector:
    app: letscode-backend
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080